# Analyzing the results of the simulations

For each type of jet and each value of $\theta_c$, the list of the resulting dictionaries is put in a Panda Dataframe.

**Input :** `all_dico_results_<jettype>_<theta_c>.pkl` where `<jettype>` = `TH` (Top-Hat), `G` (Gaussian) or `PL`(Power-Law), and `<theta_c>` = `005` (0.05 radians) or `015` (0.15 radians).

**Units :** 
- $t_{obs}$ in days,
- $F_\gamma$ in photons/cm$^2$/s.

In [1]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.patches as mpatches
import afterglowpy as grb
import math 
import pandas as pd
from astropy.cosmology import Planck18 as cosmo
from scipy.integrate import quad

## Top-Hat Jet

In [2]:
file_open = open('../data/simulations/all_dico_results_TH_015.pkl', 'rb')
configs_open = pickle.load(file_open)
file_open.close()

results_TH = pd.DataFrame(configs_open)

In [5]:
print(len(results_TH[(results_TH['axis'] == 'on') & (results_TH['t_obs'] > 4.)]))
print(len(results_TH[(results_TH['axis'] == 'on') & (results_TH['t_obs'] > 7.)]))

46
32

In [6]:
print(len(results_TH[(results_TH['axis'] == 'off') & (results_TH['t_obs'] > 4.)]))
print(len(results_TH[(results_TH['axis'] == 'off') & (results_TH['t_obs'] > 7.)]))

74
69

## Gaussian Jet
#### $\theta_c$ = 0.05 radians

In [7]:
file_open = open('../data/simulations/all_dico_results_G_005.pkl', 'rb')
configs_open = pickle.load(file_open)
file_open.close()

results_G_005 = pd.DataFrame(configs_open)

In [8]:
#pd.set_option('display.max_rows', None)
results_G_005[(results_G_005['F_gamma'] < 1.) & (results_G_005['axis'] == 'off') & (results_G_005['observable'] != 'no')]

,jetType,config,t_obs,mag_min,axis,observable,F_gamma
66,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",389.246921,19.559314,off,> 7 days,3.165389e-06
96,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",29.014368,19.694896,off,> 7 days,2.326612e-06
115,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",12.232000,21.335889,off,> 7 days,7.313369e-06
144,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",17.826394,18.226929,off,> 7 days,9.899028e-06
169,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",20.698236,23.010093,off,> 7 days,6.190267e-08
170,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",20.839607,23.631511,off,> 7 days,7.412261e-08
178,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",6.996346,20.477562,off,> 4 days,8.647466e-07
198,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",30.718659,22.586574,off,> 7 days,7.389075e-08
208,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",8.227192,24.138540,off,> 7 days,2.643295e-08
213,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",65.098173,22.041208,off,> 7 days,1.347379e-07
266,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",19.745956,22.672802,off,> 7 days,9.516200e-08
271,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",7.557591,20.249793,off,> 7 days,2.854578e-05
286,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",34.076736,21.199868,off,> 7 days,1.624081e-06
331,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",5.415085,23.705666,off,> 4 days,4.346619e-08
333,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",4.029831,23.768584,off,> 4 days,1.017377e-07
335,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",19.612004,21.926125,off,> 7 days,1.626103e-07
347,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",27.630865,16.427921,off,> 7 days,2.853908e-04
396,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",59.016578,22.906270,off,> 7 days,5.670423e-08
468,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",15.850685,24.487866,off,> 7 days,4.473582e-08
469,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",17.913887,21.364478,off,> 7 days,7.131372e-06
495,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",112.073550,18.428540,off,> 7 days,4.620622e-06
524,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",331.225068,23.917096,off,> 7 days,3.883720e-08
543,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",6.060195,19.579614,off,> 4 days,5.245465e-06
711,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",38.175895,21.147882,off,> 7 days,1.863341e-05
718,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",8.475487,21.444632,off,> 7 days,4.122289e-07
733,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",55.686421,14.445214,off,> 7 days,5.148162e-04
742,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",5.021815,23.362885,off,> 4 days,1.087976e-07
773,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",161.629873,22.778294,off,> 7 days,1.017011e-07
879,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",14.530427,21.901788,off,> 7 days,1.735618e-07
920,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",4.424294,23.162602,off,> 4 days,8.471459e-08
944,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",17.904980,23.633216,off,> 7 days,1.259455e-07
947,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",67.504856,22.158414,off,> 7 days,1.068404e-07
956,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",4.383229,23.211068,off,> 4 days,1.455061e-07

In [9]:
print(len(results_G_005[(results_G_005['axis'] == 'on') & (results_G_005['t_obs'] > 4.)]))
print(len(results_G_005[(results_G_005['axis'] == 'on') & (results_G_005['t_obs'] > 7.)]))

21
11

In [10]:
print(len(results_G_005[(results_G_005['axis'] == 'off') & (results_G_005['t_obs'] > 4.)]))
print(len(results_G_005[(results_G_005['axis'] == 'off') & (results_G_005['t_obs'] > 7.)]))

33
26

#### $\theta_c$ = 0.15 radians

In [11]:
file_open = open('../data/simulations/all_dico_results_G_015.pkl', 'rb')
configs_open = pickle.load(file_open)
file_open.close()

results_G_015 = pd.DataFrame(configs_open)

In [12]:
results_G_015

,jetType,config,t_obs,mag_min,axis,observable,F_gamma
0,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,35.906894,off,no,3.177566e-12
1,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",110.795401,24.294950,off,> 7 days,1.606979e-08
2,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,35.278966,off,no,9.458897e-12
3,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,33.071464,off,no,3.414498e-11
4,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,29.009378,off,no,7.728548e-10
...,...,...,...,...,...,...,...
995,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,31.412299,off,no,5.018328e-11
996,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,35.611053,off,no,7.171158e-12
997,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,29.523213,off,no,1.442306e-10
998,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",125.004904,11.037595,on,> 7 days,3.004032e-01
999,Gaussian,"{'jetType': 0, 'specType': 0, 'b': 4, 'thetaOb...",2.719812,17.413778,on,no,3.676328e-03

In [13]:
print(len(results_G_015[(results_G_015['axis'] == 'on') & (results_G_015['t_obs'] > 4.)]))
print(len(results_G_015[(results_G_015['axis'] == 'on') & (results_G_015['t_obs'] > 7.)]))

67
47

In [14]:
print(len(results_G_015[(results_G_015['axis'] == 'off') & (results_G_015['t_obs'] > 4.)]))
print(len(results_G_015[(results_G_015['axis'] == 'off') & (results_G_015['t_obs'] > 7.)]))

67
62

## Power-Law Jet
#### $\theta_c$ = 0.05 radians

In [15]:
file_open = open('../data/simulations/all_dico_results_PL_005.pkl', 'rb')
configs_open = pickle.load(file_open)
file_open.close()

results_PL_005 = pd.DataFrame(configs_open)

In [16]:
results_PL_005

,jetType,config,t_obs,mag_min,axis,observable,F_gamma
0,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,38.192340,off,no,5.256639e-13
1,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,25.994705,off,no,4.025163e-09
2,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,37.066933,off,no,2.755887e-12
3,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,34.808405,off,no,1.204218e-11
4,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,31.416591,off,no,1.025905e-10
...,...,...,...,...,...,...,...
995,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,33.824259,off,no,7.273595e-12
996,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,38.110332,off,no,9.746360e-13
997,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",0.000000,30.898625,off,no,5.504599e-11
998,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",34.280212,11.629209,on,> 7 days,2.021858e-01
999,PowerLaw,"{'jetType': 4, 'specType': 0, 'b': 4, 'thetaOb...",0.975872,17.412514,on,no,3.675107e-03

In [17]:
print(len(results_PL_005[(results_PL_005['axis'] == 'on') & (results_PL_005['t_obs'] > 4.)]))
print(len(results_PL_005[(results_PL_005['axis'] == 'on') & (results_PL_005['t_obs'] > 7.)]))

21
14

In [18]:
print(len(results_PL_005[(results_PL_005['axis'] == 'off') & (results_PL_005['t_obs'] > 4.)]))
print(len(results_PL_005[(results_PL_005['axis'] == 'off') & (results_PL_005['t_obs'] > 7.)]))

36
29

#### $\theta_c$ = 0.15 radians

In [28]:
file_open = open('../data/simulations/all_dico_results_PL_015.pkl', 'rb')
configs_open = pickle.load(file_open)
file_open.close()

results_PL_015 = pd.DataFrame(configs_open)

In [29]:
results_PL_015.iloc[711]['config']

{'jetType': 4,
 'specType': 0,
 'b': 4,
 'thetaObs': 0.16616312453730092,
 'E0': 6.123407761152622e+52,
 'thetaWing': 0.15719393241077656,
 'thetaCore': 0.15,
 'n0': 0.0033510057131371173,
 'p': 2.2,
 'epsilon_e': 0.1,
 'epsilon_B': 0.01,
 'xi_N': 1.0,
 'd_L': 1.0354044735824974e+27,
 'z': 0.07200000000000001}

In [24]:
print(len(results_PL_015[(results_PL_015['axis'] == 'on') & (results_PL_015['t_obs'] > 4.)]))
print(len(results_PL_015[(results_PL_015['axis'] == 'on') & (results_PL_015['t_obs'] > 7.)]))

68
49

In [25]:
print(len(results_PL_015[(results_PL_015['axis'] == 'off') & (results_PL_015['t_obs'] > 4.)]))
print(len(results_PL_015[(results_PL_015['axis'] == 'off') & (results_PL_015['t_obs'] > 7.)]))

71
66

## Table of all the results

| Jet Type | $$\theta_c$$ (rad) | Axis | $$t_{obs}$$ (days) | Number of observable afterlows (/1000) |
|:------------:|:----------:|:------:|:---------------:|:--------------------------------------:|
|**TOP-HAT**   |            | **On** |     **> 4**     |                 46                     |
|              |            |        |     **> 7**     |                 32                     |
|              |            |**Off** |     **> 4**     |                 74                     |
|              |            |        |     **> 7**     |                 69                     |
|              |            |        |                 |                                        |
|**GAUSSIAN**  |  **0.05**  | **On** |     **> 4**     |                 21                     |
|              |            |        |     **> 7**     |                 11                     |
|              |            |**Off** |     **> 4**     |                 33                     |
|              |            |        |     **> 7**     |                 26                     |
|              |  **0.15**  | **On** |     **> 4**     |                 67                     |
|              |            |        |     **> 7**     |                 47                     |
|              |            |**Off** |     **> 4**     |                 67                     |
|              |            |        |     **> 7**     |                 62                     |
|              |            |        |                 |                                        | 
|**POWER-LAW** |  **0.05**  | **On** |     **> 4**     |                 21                     |
|              |            |        |     **> 7**     |                 14                     |
|              |            |**Off** |     **> 4**     |                 36                     |
|              |            |        |     **> 7**     |                 29                     |
|              |  **0.15**  | **On** |     **> 4**     |                 68                     |
|              |            |        |     **> 7**     |                 49                     |
|              |            |**Off** |     **> 4**     |                 71                     |
|              |            |        |     **> 7**     |                 66                     |